# root_domain_name = "develop.appleupdatenotification.com"
environment = "development"
# subscription_intake_api_domain = "subscription.develop.appleupdatenotification.com"
twitter_username = "UpdateAppletest"
error_alert_email = "cullancarey@gmail.com"
