# root_domain_name = "develop.appleupdatenotification.com"
environment = "development"
# subscription_intake_api_domain = "subscription.develop.appleupdatenotification.com"
error_alert_email          = "cullancarey@gmail.com"
release_notification_email = "cullancarey@gmail.com"
