# root_domain_name = "appleupdatenotification.com"
environment = "production"
# subscription_intake_api_domain = "subscription.appleupdatenotification.com"
error_alert_email          = "cullancarey@gmail.com"
release_notification_email = "cullancarey@gmail.com"
